version: '3'
services:
  mongo:
    image: andresvidal/rpi3-mongodb3
    ports:
      - "27017:27017"
    restart: always
  mongo-service:
    build: ./mongo-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
  todolist-service:
    build: ./todolist-service
    ports:
      - "3000:3000"
  management-service:
    build: ./todo_management-service
    ports:
      - "3003:3003"
